scheduleEvent(function()
  assert(not g_game.isOnline(), 'Offline export must never run while logged in')
  g_game.setProtocolVersion(860)
  g_game.setClientVersion(860)
  g_modules.ensureModuleLoaded('game_things')
  modules.game_things.load()
  assert(g_things.isDatLoaded() and g_sprites.isLoaded(), 'DAT/SPR were not loaded')
  g_minimap.clearSatellitePack()
  g_things.loadOtbForMap('/source-items.otb')
  assert(g_things.isOtbLoaded(), 'items.otb was not loaded')
  g_map.clean()
  g_map.loadOtbm('/source-world.otbm')
  local directory = '/export-' .. os.time() .. '-' .. g_clock.millis()
  local count = g_minimap.exportSatelliteBase(directory)
  assert(count > 0, 'No image chunks were exported')
  g_minimap.saveOtmm(directory .. '/minimap.otmm')
  g_logger.info('[HD EXPORT] OUTPUT: ' .. g_resources.getWriteDir() .. directory)
  g_logger.info('[HD EXPORT] PASS: ' .. count .. ' base chunks')
  g_map.clean()
  scheduleEvent(g_app.exit, 500)
end, 1000)
